### ISSUE TITLE
File.read is missing?

### ISSUE THREAD

**Issue by mikicho** [HaxeFoundation/hxnodejs#100]
it's looks like File.read function is missing.
https://api.haxe.org/sys/io/File.html

**Comment by gene-pavlovsky** [comment]
What about https://github.com/HaxeFoundation/hxnodejs/commit/cf80c6a077e705d39f752418e95555b346f4d9b2
?

**Comment by mikicho** [comment]
Hm.. so it seems like this version didn't published on haxelib: https://lib.haxe.org/p/hxnodejs/versions/

**Comment by gene-pavlovsky** [comment]
Better try the github version before posting issue, maybe it's already done, just not released yet :)
They don't seem to release very often... Can't see why.
And make an issue and/or post on gitter to ask for a new release :)
