### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by pypmannetjies** [HaxeFoundation/hxnodejs#105]
Please update the release of the Haxelib so we can enjoy the latest changes :)

**Comment by dionjwa** [comment]
@HaxeFoundation/hxnodejs-team what is the process for this?

**Comment by andyli** [comment]
Currently only @nadako has the permission to submit according to https://github.com/HaxeFoundation/hxnodejs/blob/d518e183bce1cb2b22108d4ae09f55b2dcdb94c1/haxelib.json#L9

**Comment by ncannasse** [comment]
@nadako ping :) we need updated version to compile HIDE

**Comment by nadako** [comment]
What bothers me is that originally I wanted hxnodejs version to reflect nodejs version, but the current state is that we're somewhere inbetween 4.x and 10.x and I'm not sure if we should release that, but OTOH we don't have much manpower to update everything, so maybe we should do a release, but what version number should we use? :)

**Comment by ncannasse** [comment]
I don't think we should match nodejs version, but if you think it's better just do a minor update of the current one ;)

**Comment by Incubatio** [comment]
You could match major version number when you reached a stable state of compatibility.
To establish a state of stable compatibility, you could use a set of unit test ported from https://github.com/nodejs/node/tree/master/test/.

When doing a version upgrade, I don't think you need all the feature of the new node version, just make sure all your current feature work, bump the version and then iterate from that.

**Comment by mikicho** [comment]
> I don't think we should match nodejs version, but if you think it's better just do a minor update of the current one ;)

I think we **have** to reflect the Nodejs version because when I'm developing in hxnodejs I'm using Nodejs documentation a lot, and it can create some confusion. Again, it better to keep the versions tight.
p.s: That does not mean that we have to release every minor of Nodejs of course.

**Comment by Simn** [comment]
Yo, we really need an update. If nothing else, https://github.com/HaxeFoundation/hxnodejs/commit/9b24a891e640beca1bb57dea31800acafe696ebb#diff-a242abdf3789c4e1332bf31fdb936256 was a pretty important behavioral fix which would have saved me 2 hours just now.

Let's not get hung up on something stupid like version numbers please.

**Comment by kevinresol** [comment]
Just create a map `[hxnodejs_version => nodejs_version]` and write that clearly on readme.

**Comment by nadako** [comment]
Ok, I just released the current state as `6.9.0`, tho I'm not really sure if it contains all the 6.9.0 externs, but oh well. Also added @Simn and @Gama11 to the contributors because they are more brave than me when it comes to releasing stuff :)
