### ISSUE TITLE
if (process.version < "v4.0.0") fails in Node v10.x.y

### ISSUE THREAD

**Issue by LucasMW** [HaxeFoundation/hxnodejs#108]
node --version
v10.9.0
However: 
Module program.js requires node.js version 4.0.0 or higher

**Comment by elsassph** [comment]
Yes please - maybe it's time to just drop this test.

**Comment by LucasMW** [comment]
Back in the time, I tried removing it

> It's been dropped over a year ago ([2587ccb](https://github.com/HaxeFoundation/hxnodejs/commit/2587ccbffa3cc032d7ecca28d299e7357993f536)), there just hasn't been a new Haxelib release (#105).

Oh, that would explain a lot. I remember I tried to fix that in the repository back in the day. It looked like an easy pull request to do. However I couldn't find it anywhere in the code.
