### ISSUE TITLE
File.append() is not implemented

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/hxnodejs#120]

**Comment by terurou** [comment]
#143

**Comment by JaviCerveraIngram** [comment]
Is this library still active? No response since april...

**Comment by sebpatu** [comment]
hi please add it.
its straight forward: implementation like write with different flag:
`
public static inline function append(path:String, binary:Bool = true):FileOutput 
{
	return new FileOutput(Fs.openSync(path, AppendCreate));
}
`
Thanks

**Comment by Gama11** [comment]
@sebpatu Pull request?
