### ISSUE TITLE
Some `js.*` types moved to `js.lib.*`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/hxnodejs#122]
See https://github.com/HaxeFoundation/haxe/pull/7390
hxnodejs needs to be updated.

**Comment by kevinresol** [comment]
Can we stay with Haxe Date?

**Comment by RealyUniqueName** [comment]
Some warnings still come from `js.Date`. 
Like these: 
https://github.com/HaxeFoundation/hxnodejs/blob/df81c3892dae70cc513122b2169e71867b1b2b08/src/js/node/fs/Stats.hx#L39-L67
Should all of `js.Date` references to be replaced with Haxe Date?

**Comment by kevinresol** [comment]
in fact `js.Date` was the breaking change. we are just undoing it.
