### ISSUE TITLE
remove @:fakeEnum

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/hxnodejs#124]
let's remove it from haxe in favor of extern enum abstracts (https://github.com/HaxeFoundation/haxe/pull/8189). i think they will just work with recent haxe 3 too, so there's no need to fence it even

**Comment by Gama11** [comment]
As far back as 3.2.1? https://github.com/HaxeFoundation/hxnodejs/blob/master/.travis.yml#L7

**Comment by nadako** [comment]
not sure about 3.2.1 but i think it's fair to drop it for new versions anyway
