### ISSUE TITLE
Haxe 4 Error

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxnodejs#131]
```hxnodejs\6,9,1\src\js/node/Dns.hx:131: lines 131-251 : @:fakeEnum enums is no longer supported in Haxe 4, use extern enum abstract instead```

This also requires pushing a new version to haxelib ;)

**Comment by ncannasse** [comment]
`js/node/stream/Writable.hx:135: characters 66-74 : Warning : This typedef is deprecated in favor of js.lib.Error`

And many (many) warnings as well ;)

**Comment by Gama11** [comment]
These things have been fixed for quite a while on GitHub. We can't make a new Haxelib release of hxnodejs until rc.3 happens.
