### ISSUE TITLE
Breaks browser (or other js environments than node.js)

### ISSUE THREAD

**Issue by cancerberoSgx** [HaxeFoundation/hxnodejs#133]
Hello, I'm trying to support all targets in the same API and for that needed to implement some wrappers / macros for emulating Sys stuff in node.js. I also need to support the browser. I just tried this library and it works OK (I can call Sys directly from node.js but unfortunately it will break the browser `ERROR: ReferenceError: Can't find variable: require`. It seems that the genreated .js code is different and doesn't emulate `require()` as without the library. This is needed by the browser (nodej is fine). Do you know any workaround for this? like forcing it to be global or something like that? I'm using node 12.3.1 haxe Compiler 4.0.0-rc.3+68333d85d  and a few lightweight haxelibs. for sys targets I?m removing this library and for node and browser I need to add it (since the target is the same I can't differentiate but I need to support both. Probably I don't need to use Sys APIs in the browser but it won't compile and I don't want to have different implementations one for node.js and other for browsers. Thanks in advanced.

**Comment by Gama11** [comment]
I don't really follow... why would you have `-lib hxnodejs` if you're not targeting nodejs / the browser?

**Comment by cancerberoSgx** [comment]
I'm targeting all, cpp, node.js, browser, java, etc. 
* I want to write the API in the same project. When running serverside it reads filesystem, process.argv, when in the browser it reads from DOM , request, local storage, etc. 
I don't want to split in different projects since 90% of the code is shared.
* The "native sys" part is encapsulated in a single file which until now I was able to manage it with macros / conditionaly compilation.
* today I tried this library and realized I can just use Sys.* in node too so I can get rid of those conditional macros
* but adding -lib hxnodejs makes the output js code not to export require()
* I tried to create a second .hxml project just for the browser, without -libhxnodejs , but since now my js (conditional code) is accessing Sys.* it won't compile unless I add -lib hxnodejs.

Is this the expected behavior (adding the library removes require())? Is there a workaround ? 

The next thing I'm gonna try is to bundle it with browserify perhaps that solves the issue, but I don't think so. Also other ways of conditionally import this entire file if not in the browser with a compiler flag.

perhaps I'm too ambitious trying the same project to target everything?. Is not a blocker for me since I can continue working with my conditional compiled shared code as so far, but if this issue can be solved It would be much cleaner to work with this library

Hope you get it , thanks in advance.

**Comment by Gama11** [comment]
I think you're on the right track with having different hxml files for browser and node.js builds. If you have some browser-specific sys implementation, it sounds like what you might be missing is `--macro allowPackage('sys')` that including hxnodejs adds automatically.

**Comment by cancerberoSgx** [comment]
Thanks, I'm not sure if adding that flag made the trick but I'm able to consume the library as an external application  "haxelib install"ing it. That's enough for me since I can test the browser and move the browser's test into separate projects. A phantom js script was failing too but probably could be refactored a little bit  since investigating I was wrong in my assumption that this library was removing require() at all, my bad. Thanks again. The important part is I have the same code for node.js and the rest of the sys languages and also I'm able to test the browser. Thanks

**Comment by Gama11** [comment]
Huh? You didn't use it as a Haxelib before?

**Comment by cancerberoSgx** [comment]
I have my tests and code in the same project, I'm new to haxe but it's pretty common in other languages to have both things together though. The tests were the ones start failing (still not quite sure why) . I only test it as haxelib before publishing, but regularly I run tests as part of the same project as the code.

**Comment by Gama11** [comment]
Ah, it sounded like you were talking about hxnodejs itself (using it as a `-cp` directly instead of `-lib` or something).

**Comment by cancerberoSgx** [comment]
no, I'm sorry I'm lazy today to explain and hard to understand in general ;) I was using it as -lib  thanks
