### ISSUE TITLE
implement sys.io.Process

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/hxnodejs#174]
Is it possible to implement the sys.io.Process API for hxnodejs?

**Comment by NQNStudios** [comment]
I've started sketching out how I might do this myself...

```
import js.node.ChildProcess;
import js.node.child_process.ChildProcess as ChildProcessObject;

class NodeProcess {
    // https://github.com/HaxeFoundation/hxnodejs/blob/master/src/js/node/child_process/ChildProcess.hx
    var process:ChildProcessObject;

    public function new(cmd:String, ?args:Array<String>, ?detached:Bool) {
        process = ChildProcess.spawn(cmd, args, {detached: detached});
    }

    // TODO provide stderr by wrapping process's stderr js.node.stream.IReadable in an object that implements haxe.io.Input
    // TODO provide stdin by wrapping process's stdin js.node.stream.IWriteable in an object that implements haxe.io.Output
    // TODO provide stdout by wrapping process's stdout js.node.stream.IReadable in an object that implements haxe.io.Input

    // TODO provide close() by calling process's disconnect() method
    // TODO provide kill() by calling process's kill() method
    // TODO not sure how to provide exitCode(), which has no equivalent in ChildProcessObject
}
```

I'm stumped on how to get the exit code from a ChildProcessObject. Everything else I think I can do, if I just put the time in and muddle through it.

If I could implement this feature, would it be merged @nadako?

**Comment by nadako** [comment]
If it works - then yeah I guess :) Tho `sys.io.Process` is awkward, I thought nobody uses it ^^

**Comment by NQNStudios** [comment]
I use it as a cross-target interface for running console commands. Is there something better for that, or do people just use target-specific APIs like node's `child_process`?

**Comment by NQNStudios** [comment]
After implementing and testing my proposed approach, I'm convinced it's not actually possible to provide Process's synchronous API in single-threaded JavaScript.
