### ISSUE TITLE
it wont work?

### ISSUE THREAD

**Issue by lolBoi9696** [HaxeFoundation/hxnodejs#177]
![image](https://user-images.githubusercontent.com/76548041/129998895-9cc50bdc-71a2-4a2c-8962-69e1b8473f47.png)
it causes this error when i use this

**Comment by Gama11** [comment]
Where is that screenshot from - a browser...?

**Comment by lolBoi9696** [comment]
> Where is that screenshot from - a browser...?

yeah?

**Comment by Gama11** [comment]
That can't work, Chrome / browsers in general are not a NodeJS environment.

**Comment by lolBoi9696** [comment]
> That can't work, Chrome / browsers in general are not a NodeJS environment.

no im not running it on chrome im viewing it on chrome

**Comment by Gama11** [comment]
I'm not sure how there can be a difference between viewing and running?

**Comment by lolBoi9696** [comment]
> I'm not sure how there can be a difference between viewing and running?

i compiled and ran it with the vscode extension
it opens up chrome and yeah everything works but when i install this it doesnt

**Comment by Gama11** [comment]
If it opens up chrome, the code is _running in Chrome_.

>how do i load a file in haxe with js

This isn't the right place to discuss questions like that, try one of the community channels like the forum or the discord: https://haxe.org/foundation/contact.html

**Comment by lolBoi9696** [comment]
> If it opens up chrome, the code is _running in Chrome_.
> 
> > how do i load a file in haxe with js
> 
> This isn't the right place to discuss questions like that, try one of the community channels like the forum or the discord: https://haxe.org/foundation/contact.html

no the vscode extension builds it with lime and runs it with lime it setups a web server
