### ISSUE TITLE
Release to haxelib following pr #190

### ISSUE THREAD

**Issue by theJenix** [HaxeFoundation/hxnodejs#191]
Wasn't sure the right way to request this; apologizes if this creates issue noise!  Can y'all release a new version of hxnodejs to lib.haxe.org that incorporates https://github.com/HaxeFoundation/hxnodejs/pull/190?  This would clean up a lot of build warnings for me and I'd imagine many others who have since migrated to Haxe 4.3.

Thanks!

**Comment by RblSb** [comment]
@Gama11 can you please release it?

**Comment by yuxiaomao** [comment]
Hello, any news?

**Comment by yuxiaomao** [comment]
@nadako could you please look at this?

**Comment by kLabz** [comment]
Released 12.2.0 https://lib.haxe.org/p/hxnodejs/12.2.0/
