### ISSUE TITLE
node 0.12

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/hxnodejs#33]
so, node 0.12 released before hxnodejs and we need to adapt externs for the new version

**Comment by nadako** [comment]
the question is - should we be compatible with 0.10 or not

**Comment by nadako** [comment]
http://blog.nodejs.org/2015/02/06/node-v0-12-0-stable/
https://github.com/joyent/node/wiki/API-changes-between-v0.10-and-v0.12

**Comment by Simn** [comment]
That doesn't look too bad.

**Comment by eduardo-costa** [comment]
we gonna make a new branch or add some #ifdefs ?
Em 24/02/2015 16:09, "Simon Krajewski" <notifications@github.com> escreveu:

**Comment by nadako** [comment]
I'm not sure yet. I think a couple of `#if`s should be enough.

**Comment by eduardo-costa** [comment]
If the change is small I think it is easier too.

Maybe in a major release we should branch then.

2015-02-24 16:35 GMT-03:00 Dan Korostelev <notifications@github.com>:

> I'm not sure yet. I think a couple of #ifs should be enough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/hxnodejs/issues/33#issuecomment-75828867>
> .
>



-- 
[image: Imagem inline 1]

**Comment by fponticelli** [comment]
I think we should stick to 0.12 and forget about 0.10. NodeJS users update frequently.

**Comment by Simn** [comment]
I don't see the harm in supporting both if it's a matter of adding some conditional compilation.

**Comment by nadako** [comment]
Upgrading to 0.12...
