### ISSUE TITLE
Promise exist in v.0.12 but they are not defined externs

### ISSUE THREAD

**Issue by ponticelli** [HaxeFoundation/hxnodejs#34]
They do also exist in js.html.Promise so an alias might be sufficient.

**Comment by nadako** [comment]
as we talked on `#haxe-dev`, it should really `js.Promise` available in core haxe (instead of `js.html.Promise`)

**Comment by fponticelli** [comment]
So I should probably open an issue there :)

Il giorno mar 10 mar 2015 alle ore 15:10 Dan Korostelev <
notifications@github.com> ha scritto:

**Comment by nadako** [comment]
impostor!

**Comment by fponticelli** [comment]
Split personality :)
