### ISSUE TITLE
adapt to node 4.0.0

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/hxnodejs#41]
https://nodejs.org/en/blog/release/v4.0.0/

**Comment by waneck** [comment]
How will we handle versioning in hxnodejs? Will we use `@:require`? Or separate branches?

**Comment by nadako** [comment]
well, for this particular nodejs release (which is long-term-support) i tend to just adapt hxnodejs to latest apis and finally do the haxelib release, for further releases I think branches would be better than `@:require` branching spaghetti.

**Comment by eduardo-costa** [comment]
I think Git branches is also more manageable!

2015-09-08 17:40 GMT-03:00 Dan Korostelev <notifications@github.com>:

> well, for this particular nodejs release (which is long-term-support) i
> tend to just adapt hxnodejs to latest apis and finally do the haxelib
> release, for further releases I think branches would be better than
> @:require branching spaghetti.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/hxnodejs/issues/41#issuecomment-138692944>
> .
>



-- 
[image: Imagem inline 1]

**Comment by nadako** [comment]
4.1.0 https://nodejs.org/en/blog/release/v4.1.0/

**Comment by nadako** [comment]
Tho there seem to be no API changes.

**Comment by nadako** [comment]
hxnodejs is now targetting nodejs 4.0+
