### ISSUE TITLE
Compiler complains that `.flag`don't exists but it is defined in `Fs*FileOptions`

### ISSUE THREAD

**Issue by eduardo-costa** [HaxeFoundation/hxnodejs#43]
`Fs.hx`
```
var opt : FsWriteFileOptions = cast { };		
opt.flag = FsOpenFlag.AppendReadCreate;		
```
`js.node.FsWriteFileOptions has no field flag`

**Comment by nadako** [comment]
Thanks! Btw you don't need a `cast` there since all fields are optional in that structure.

**Comment by eduardo-costa** [comment]
Old habits :)
Em 12/09/2015 06:14, "Dan Korostelev" <notifications@github.com> escreveu:
