### ISSUE TITLE
Move non-api classes from hxnodejs to hxnodelibs

### ISSUE THREAD

**Issue by eduardo-costa** [HaxeFoundation/hxnodejs#45]
If we start to add `npm` stuff in `hxnodejs` the lib will quickly become bloated and hard to manage.
I think we should keep libraries externs in another repository and keep `hxnodejs` focused only in the official functionalities.

**Comment by nadako** [comment]
This is done now, isn't it?

**Comment by eduardo-costa** [comment]
Yep seems correct!
