### ISSUE TITLE
sys.FileSystem.createDirectory() should be recursive.

### ISSUE THREAD

**Issue by jeremyfa** [HaxeFoundation/hxnodejs#51]
Current implementation is using `Fs.mkdirSync()` which will fail if some intermediate directories don't exist, while haxe API docs are stating that `createDirectory()` is recursive.

I guess a solution might be to implement something similar to this: https://github.com/substack/node-mkdirp/blob/master/index.js

Thanks for the great work anyway!

**Comment by nadako** [comment]
Thanks for the report, I'll fix that.

**Comment by jeremyfa** [comment]
👍
