### ISSUE TITLE
accessSync vs existsSync

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxnodejs#53]
I had to add the following on CastleDB:
```
untyped if( js.node.Fs.accessSync == null ) js.node.Fs.accessSync = (js.node.Fs : Dynamic).existsSync;
```
Not sure if we want to support this kind of backward compatibility or not. The issue in that case is that sys.FileSystem.exists was failing silently because of the catch( Dynamic )

**Comment by nadako** [comment]
I'm not sure we want to support that either. IIRC, `access(Sync)` was added in node 0.12 which is quite old nowadays and we officially support 4.0+

**Comment by clemos** [comment]
I dont think we should support that either.
But I went through such weird (silent and difficult to track down) issues with older nodejs versions too,
and I think it would be very nice to print a warning at runtime in case of version mismatch.

**Comment by clemos** [comment]
I've been quickly trying to implement version check, but I'm not sure how to do it.
`haxe.macro.Compiler.includeFile()` doesn't seem to work in hxml / extraParams.hxml (?).
Then I guess there should be a kind of `Boot` class for nodejs, ie a class that gets included at every compilation.
But how (extraParams.hxml ?), and what name (`js.node.Boot` ? `js.NodeBoot` ? we can't shadow `js.Boot` obviously...) ?
What do you think ?

**Comment by nadako** [comment]
I'd like to avoid adding any unnecessary code in the generated js just to support old node 0.10...

**Comment by nadako** [comment]
Oh, you're talking about simple version checking.

**Comment by nadako** [comment]
BTW, @ncannasse, are you sure your fix works properly? Because `access` either throw exception or does nothing, while `exists` doesn't throw exceptions but returns bool instead.

**Comment by ncannasse** [comment]
Ah, right maybe it should be patched differently then.

**Comment by clemos** [comment]
@nadako yes I'm just talking about injecting something like that (pseudo code...) at the beginning of every Haxe generated JS : 
```
if( process.version < 4 ) console.warn("Warning: This script requires nodejs 4.0+");
```

**Comment by nadako** [comment]
I added the check and it seems to work (please test), however I would like to be able to disable generation of this, since I actually have to use node 0.12 for now and while it's not fully compatible (e.g. Buffer<-Uint8Array), a large part of hxnodejs is still usable with it.

I tried to make a macro that does `Context.defined` check and then `Compiler.includeFile`, but for some reason it just doesn't include anything. Any ideas?

**Comment by nadako** [comment]
See HaxeFoundation/haxe#4660
