### ISSUE TITLE
version warning

### ISSUE THREAD

**Issue by clemos** [HaxeFoundation/hxnodejs#55]
produces this : 
```
/home/clemos/Work/hxnodejs/src/_hxnodejs/VersionWarning.hx:9: characters 12-86 : Primitive not found macro@include_file:2
--macro:1: character 0 : Called from
Aborted
```
using haxe 3.2.1 (installed from official deb) + neko 2.0

**Comment by nadako** [comment]
Somewhat related to #54, since it seems that this is not tested on Travis because of missing extraParams.hxml processing.
