### ISSUE TITLE
Sys.args() length inconsistent across target?

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/hxnodejs#57]
In php target, `Sys.args()` returns only the "arguments", i.e. exclude the executable and the script.
For example it will return `['arg1', 'arg2', 'arg3']` for the command `php script.php arg1 arg2 arg3`

However, in hxnodejs, `Sys.args()` returns `process.argv;` which include the executable and the script.
For example the command `node script.js arg1 arg2 arg3` will become `['node', 'script.js', 'arg1', 'arg2', 'arg3']`

Ref:
http://php.net/manual/en/reserved.variables.argv.php
https://github.com/HaxeFoundation/haxe/blob/development/std/php/_std/Sys.hx#L34

**Comment by nadako** [comment]
@Simn @ncannasse do we specify this somehow? The doc says simply `Returns all the arguments that were passed by the commandline.`

**Comment by ncannasse** [comment]
It's not specified this way but yes it means that it should only be the arguments that are to be processed, so I agree that it should be fixed for nodejs

**Comment by nadako** [comment]
I wonder what `Sys.args()` return for unix executable scripts run through shebang (`#!/usr/bin/node`)...
