### ISSUE TITLE
Headers type in IncomingMessage'

### ISSUE THREAD

**Issue by JbIPS** [HaxeFoundation/hxnodejs#61]
I saw that in recent update, `Http.headers` had became `EitherType<String, Array<String>>`, I suppose to support the `set-cookie` header which is an array.

But I'm wondering why this haven't been changed in [`IncomingMessage`](https://github.com/HaxeFoundation/hxnodejs/blob/master/src/js/node/http/IncomingMessage.hx#L56). Was there a compatibility issue? If not, I'll make a PR to change it as well.

Thank you

**Comment by nadako** [comment]
Looks like an oversight, PR welcome :)
