### ISSUE TITLE
research `deasync` library for implementing haxe sync apis

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/hxnodejs#64]
see https://www.npmjs.com/package/deasync

**Comment by sledorze** [comment]
Nooooooooooooooooooooooooooooooooo! :)

**Comment by nadako** [comment]
Hahaha :) Well, what's the alternative?:)

**Comment by nadako** [comment]
Let's not go that way. For file i/o we already support sync API using `fs.*Sync` methods on file descriptors directly.
