### ISSUE TITLE
byteLength defined as static node Buffer and defined as member in ArrayBufferView

### ISSUE THREAD

**Issue by wighawag** [HaxeFoundation/hxnodejs#65]
C:\HaxeToolkit\haxe\lib\hxnodejs/4,0,4/src/js/node/buffer/Buffer.hx:65: characters 8-65 : Same field name can't be use for both static and instance : byteLength

haxe 3.3

**Comment by nadako** [comment]
What haxe commit are you on? Using same name for static and instance fields is allowed on haxe 3.3 for quite long time now (the hxnodejs change is from Nov 2015 aa1dc57c17803ed67cf1af39b93f31d4b5acdebd)

**Comment by wighawag** [comment]
I am not sure, using Kha haxe fork, I guess you can ignore
