### ISSUE TITLE
Sys.print is defined as accepting Dynamic but nodejs only acccept string

### ISSUE THREAD

**Issue by wighawag** [HaxeFoundation/hxnodejs#68]
When doing 

```
Sys.println(["test","test2"]);
```

I got  at runtime :

```
throw new TypeError('invalid data');
```

as stdout.write only accept strings

**Comment by nadako** [comment]
Oh, I probably assumed it does implicit `toString`, but apparently not, so we have to do `Std.string` before. I'll look if there are more optimal ways though...
