### ISSUE TITLE
provide haxe.Http implementation

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/hxnodejs#69]
code here: https://github.com/HaxeFoundation/haxe/pull/4713

**Comment by Blank101** [comment]
I would advise against overriding the Http class. I've seen this done before, and it leads to desynchronization of the code in the long run. This PR should be merged into the Haxe repo until Http is split into platform specific code.

**Comment by nadako** [comment]
Well, hxnodejs is HF supported, so I think we could maintain this properly.

**Comment by nadako** [comment]
This can't be done because of #42, so I merged the haxe PR.
