### ISSUE TITLE
Missing sys.io.FileInput/FileOutput implementationts

### ISSUE THREAD

**Issue by cambiata** [HaxeFoundation/hxnodejs#89]
@nadako Are these to be expected? Soon? :-)

**Comment by nadako** [comment]
I worked on this a bit [here](https://github.com/HaxeFoundation/hxnodejs/blob/master/src/Sys.hx#L119) and it seems to work (though I haven't tested it much). I guess just need to add teel/seek methods...

**Comment by cambiata** [comment]
Thanks, Dan!

FYI, @benmerckx pointed out his asys implementation:
https://github.com/benmerckx/asys/tree/master/asys/io

**Comment by mikicho** [comment]
@nadako Please close this issue as those classes are fully implemented now.

**Comment by nadako** [comment]
Alright :)
