### ISSUE TITLE
who want some cookies!

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/hxnodejs#95]
Hello!

I quickly wrote an extern for the node.js cookie ( https://www.npmjs.com/package/cookie ), can I make a pull request or maybe it should be somewhere else ?

Thanks !

**Comment by nadako** [comment]
Hey! `hxnodejs` is only for bundled node.js APIs, for an npm package I'd propose you do a library like e.g. my [hxnodejs-commander](https://github.com/nadako/hxnodejs-commander). Alternatively you can contribute to https://github.com/clemos/haxe-js-kit or https://github.com/HaxeFoundation/hxnodelibs

**Comment by delahee** [comment]
Super cool, thanks! I ll go with hxnodelibs. See ya!
