### ISSUE TITLE
Wrong annotation of 'update' method in  'js.node.crypto.Hmac' extern class.

### ISSUE THREAD

**Issue by djaonourside** [HaxeFoundation/hxnodejs#96]
js.node.crypto.Hmac update method should return Hmac type. Now it returns Void. Here usage from node.js doc:
`const hash = crypto.createHmac('sha256', secret)
                      .update('I love cupcakes')
                      .digest('hex');`

**Comment by mikicho** [comment]
Are you sure? according to the [docs ](https://nodejs.org/docs/latest-v10.x/api/crypto.html#crypto_hmac_update_data_inputencoding) it seems like `update` returns nothing.

**Comment by djaonourside** [comment]
@mikicho ts types says 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6d9d1c7a924548017fa3c23959c7dac4492c2e85/types/node/index.d.ts#L5895

**Comment by nadako** [comment]
Yeah, it should, see https://github.com/nodejs/node/blob/93925353f8af7f6d5c99537a71f9a3fe9cf5f795/lib/internal/crypto/hash.js#L64. Thanks for the PR!
